#Configuration
settings:

    minio_key: #Replace with your access_key_id
    minio_access: #Replace with secret_access_key
    
    
locations:

    db_path: ./data/local.db
    server_path: #Replace with your S3 or S3-like (e.g., minio) Server Path
    server_bucket: #Replace with Your Bucket Name
    server_region: #Replace with Your S3 or S3-like Server Region
    
    
configuration:
    
    oanda: https://api-fxtrade.oanda.com/v3/instruments/
    authorization:   # Replace with Your Oanda API Key
    granuality: H1  # See https://developer.oanda.com/rest-live-v20/instrument-df/#CandlestickGranularity
    data_start: 9  # Oanda API time (Start Hour)
    data_end: 17  # Oanda API time (End Hour)
    price: M     # See https://developer.oanda.com/rest-live-v20/primitives-df/#PricingComponent
    



