#Configuration
settings:

    minio_key: #Replace with Your Key
    minio_access: #Replace with Access
    
    
locations:

    db_path: ./data/local.db
    server_path: #Replace with Minio Server
    server_bucket: #Replace with Your Bucket Name
    
    
configuration:
    
    oanda: https://api-fxtrade.oanda.com/v3/instruments/
    authorization:   #Replace with Your API Key
    granuality: H1  #See https://developer.oanda.com/rest-live-v20/instrument-df/#CandlestickGranularity
    data_start: 9  #Oanda API time (Start Hour)
    data_end: 17  #Oanda API time (End Hour)
    



